CREATE TABLE IF NOT EXISTS words (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  quebecois TEXT NOT NULL,
  standard_french TEXT NOT NULL,
  english TEXT NOT NULL,
  pronunciation TEXT,
  usage_notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);